# Third Session, Notebook # 5: Introduction to Python Structures

## Today's agenda:
0. __Workshop Overview__:
    * __When__: August 14th, 12pm-5pm
    * __Where__: CUNY Graduate Center, Room 5382
    * __What__: Introduction to Python structures
    * __Want__ to lead a session for a topic? Some Days there will be small hack sessions for people to discuss problems they're working on.
    * __Online Resources__:  __https://daxfeliz.github.io/cunybridgebootcamp/__
    * __Program Schedule__: __https://tinyurl.com/mu88x9xc__
&nbsp;


1. __This session__:
* Basics of Python
* List Comprehension
* Dictionaries
* Functions
* Classes
</br>
&nbsp;

2. __Next session__:
    * Data Manipulation & LaTeX and Overleaf! __Make sure you bring your laptop to this session and future sessions__.



# Basics of Python

## The minimal Python script
Unlike many other languages, a simple Python script does not require any sort of header information in the code. So, we can look at the standard programming example, Hello World, in Python (below). Here we're simply printing to screen. If we put that single line into a blank file (called, say, HelloWorld.py]) and then run that in the command line by typing 'python HelloWorld.py' the script should run with no problems. This also shows off the first Python function, print, which can be used to print strings or numbers.

In [1]:
print("Hello World!") 

Hello World!


## There are different types of object classes in Python. Below are a few examples:

In [2]:
print( type("Hello World") ) #'str' is short for string

<class 'str'>


In [3]:
print(1 , 'type:' , type(1) ) # 'int' is short for integer
print(' ')
print(1.25 , 'type:' , type(1.25) ) # float is for numbers that have digits (AKA floating numbers)

1 type: <class 'int'>
 
1.25 type: <class 'float'>


There are, however, a few lines that you will usually see in a Python script. The first line often starts with `"#!"` and is called the "shebang". For a Python script (a `.py` file), an example of the shebang line would be `"#!/usr/bin/env python"`

Within Python, any line that starts with `"#"` is a comment, and won't be executed when running the script. The shebang, though, is there for the shell. If you run the script by calling python explicitly, then the script will be executed in Python. If, however, you want to make the script an executable (which can be run just by typing `"./HelloWorld.py"`) then the shell won't know what language the script should be run in. This is the information included in the shebang line. You don't need it, in general, but it's a good habit to have in case you ever decide to run a script as an executable.

Another common thing at the starts of scripts is several lines that start with `'import'`. These lines allow you to allow import individual functions or entire modules (files that contain multiple functions). These can be those you write yourself, or things like numpy, matplotlib, etc.


## Python variables

Some languages require that every variable be defined by a variable type. For example, in C++, you have to define a variable type, first. For example a line like "int x" would define the variable x, and specify that it be an an integer. Python, however, using dynamic typing. That means that variable types are entirely defined by what the variable is stored.

In the below example, we can see a few things happening. First of all, we can see that x behaves initally as a number (specifically, an integer, which is why 42/4=10). However, we can put a string in there instead with no problems. However, we can't treat it as a number anymore and add to it.

Try "Un-Commenting" the 5th line (print x+10) by removing the # to the front of that line, and we'll see that Python will still add *strings* to it.

In [4]:
#with numbers we can do numerical operations
x=42

print(x , 'type:' , type(x))
print(' ')

print (x+10 , 'type:' , type(x+10))
print(' ')

print (x/4 , 'type:' , type(x/4))# since this value is not an integer, Python will convert it to a float object
print(' ')

# we can also do add strings together although it won't change the content of the strings 
# but rather append them together
x="42"
print(x, 'type:' , type(x))
print(' ')
# print (x+10) # Note: you cannot add strings (inputs that are surrounded by quotes) to non-string objects
print (x+"10", 'type:' , type(x+"10"))
print(' ')

# Note: these numerical operations won't work on strings, 
# try removing the hash tags below and see what outputs we get:
# print (x-"10")
# print(' ')
# print (x*"10")
# print(' ')

42 type: <class 'int'>
 
52 type: <class 'int'>
 
10.5 type: <class 'float'>
 
42 type: <class 'str'>
 
4210 type: <class 'str'>
 


# Booleans
Booleans have a one of two states,"True" or "False". Try setting a variable equal to True or False in the box below - you should see Python "color" the word to indicate syntactically that it is a special word in Python that has a specific meaning.

In [5]:
T = True
F = False 

print(T , 'type:' , type(T))
print(F , 'type:' , type(F))

True type: <class 'bool'>
False type: <class 'bool'>


## Lists
The basic way for storing larger amounts of data in Python (and without using other modules like numpy) is Python's default option, lists. A list is, by its definition, one dimensional. If we'd like to store more dimensions, then we are using what are referred to as lists of lists. This is *not* the same thing as an array, which is what numpy will use. Let's take a look at what a list does.

We'll start off with a nice simple list below. Here the list stores integers. Printing it back, we get exactly what we expect. However, because it's being treated as a list, not an array, it gets a little bit weird when we try to do addition or multiplication. Feel free to try changing the operations that we're using and see what causes errors, and what causes unexpected results.

In [6]:
x=[1, 2, 3]
y=[4, 5, 6]
print ('x:' , x)
print ('y:' , y)
print(' ')

# what happens when we perform numerical operations on a list?

print ('x*2:' , x*2) # this will repeat the contents of the list twice, instead of multiplying each entry by 2
print(' ')

print ('x+y:', x+y) # this will append the y list to the x list, instead of adding each entry to each other
print(' ')

print ('y+x:', y+x) # similar as above except we are now appending the x list to the y list
print(' ')

x: [1, 2, 3]
y: [4, 5, 6]
 
x*2: [1, 2, 3, 1, 2, 3]
 
x+y: [1, 2, 3, 4, 5, 6]
 
y+x: [4, 5, 6, 1, 2, 3]
 


We can also set up a quick list if we want to using the range function. If we use just a single number, then we'll get a list of integers from 0 to 1 less than the number we gave it.

If we want a bit fancier of a list, then we can also include the number to start at (first parameter) and the step size (last parameter). All three of these have to be integers.

If we need it, we can also set up blank lists.

In [7]:
import numpy as np


print(' A linearly spaced array, from 0 to 10 with 11 evenly spaced numbers: \n', np.linspace(0,10,11))


 A linearly spaced array, from 0 to 10 with 11 evenly spaced numbers: 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


If we want to, we can refer to subsets of the list. For just a single term, we can just use the number corresponding to that position. 

__An important thing with Python is that the list index starts at 0, not at 1, starting from the first term__.

If we're more concerned about the last number in the list, then we can use negative numbers as the index. The last item in the list is -1, the item before that is -2, and so on.


We can also select a set of numbers by using a : to separate list indices. If you use this, and don't specify first or last index, it will presume you meant the start or end of the list, respectively.

After you try running the sample examples below, as an exercise, try to get the following results:
* [6] (using two methods)
* [3,4,5,6]
* [0,1,2,3,4,5,6]
* [7,8,9]

In [8]:
# x=range(1,11)
x=np.linspace(0,10,11)
print ('x: ', x,'\n')
print ("First value of x:", x[0],'\n')
print ("Last value of x:", x[-1],'\n')
print ('First 5 values of x:', x[0:5],'\n')
print ("Fourth to sixth values of x:", x[3:6],'\n')


x:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

First value of x: 0.0 

Last value of x: 10.0 

First 5 values of x: [0. 1. 2. 3. 4.] 

Fourth to sixth values of x: [3. 4. 5.] 



## Modifying lists

The simplest change we can make to a list is to change it at a specific index just be redefining it, like in the second line in the code below.

There's three other handy ways to modify a list. append will add whatever we want as the next item in the list, but this means if we're adding more than a single value, it will add a list into our list, which may not always be what we want.

extend will expand the list to include the additional values, but only if it's a list, it won't work on a single integer (go ahead and try that).

Finally, insert will let us insert a value anywhere within the list. To do this, it requires a number for what spot in the list it should go, and also what we want to add into the list.

In [9]:

x=[1,2,3,4,5]
print('x:', x)
print(' ')

# let's change the 3rd element from 3 to 8
print('Testing index re-writing (replacing 3rd element with 8):')
x[2]=8
print (x)
print(' ')

# let's append the number 6 to our list
print ("Testing appending of a single index value (adding 6 to end of list):")
x.append(6)
print (x)
print(' ')

# let's append a 2nd list to our list
print ("Testing appending of a single index list (adding sub-list [7,8] to our list):")
x.append([7,8])
print (x)
print(' ')

# let's say we want to add more than 1 value to our list, not append a sublist. We can use ".extend" instead
print ("Testing extend (redefining x then extending 7,8 to end):")
x=[1,2,3,4,5]
print(x)
#x.extend(6)
# print(' ')
x.extend([7,8])
print (x)
print(' ')

# we can also use '.insert' to inster values to entries in our list
print ("Testing insert (redefining x and inserting 'in' after the value 2):")
x=[1,2,3,4,5]
x.insert(2, "in")
print (x)
print(' ')

x: [1, 2, 3, 4, 5]
 
Testing index re-writing (replacing 3rd element with 8):
[1, 2, 8, 4, 5]
 
Testing appending of a single index value (adding 6 to end of list):
[1, 2, 8, 4, 5, 6]
 
Testing appending of a single index list (adding sub-list [7,8] to our list):
[1, 2, 8, 4, 5, 6, [7, 8]]
 
Testing extend (redefining x then extending 7,8 to end):
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 7, 8]
 
Testing insert (redefining x and inserting 'in' after the value 2):
[1, 2, 'in', 3, 4, 5]
 


# Lists vs Arrays:

<img src="./images/lists_vs_arrays.png" width="100%">

# Example

In [10]:
print('testing list 1 and array 1:')
list_1 = [ 1, 'A', True, 2.5]

print(list_1)
print('')

for L in list_1:
    print(L , 'type:', type(L))
print(' ')

array_1 = np.array(list_1)
for A in array_1:
    print(A , 'type:', type(A))
print(' ')

# try a different list

print('testing list 2 and array 2:')
list_2= [ False, True, 2]

print(list_2)
print('')

for L in list_2:
    print(L , 'type:', type(L))
print(' ')

array_2 = np.array(list_2)
for A in array_2:
    print(A , 'type:', type(A))
print(' ')


print('testing list 3 and array 3:')
list_3= [ 1.23, 4.56, 7.89, 'wordy word']

print(list_3)
print('')

for L in list_3:
    print(L , 'type:', type(L))
print(' ')

array_3 = np.array(list_3)
for A in array_3:
    print(A , 'type:', type(A))
print(' ')

testing list 1 and array 1:
[1, 'A', True, 2.5]

1 type: <class 'int'>
A type: <class 'str'>
True type: <class 'bool'>
2.5 type: <class 'float'>
 
1 type: <class 'numpy.str_'>
A type: <class 'numpy.str_'>
True type: <class 'numpy.str_'>
2.5 type: <class 'numpy.str_'>
 
testing list 2 and array 2:
[False, True, 2]

False type: <class 'bool'>
True type: <class 'bool'>
2 type: <class 'int'>
 
0 type: <class 'numpy.int64'>
1 type: <class 'numpy.int64'>
2 type: <class 'numpy.int64'>
 
testing list 3 and array 3:
[1.23, 4.56, 7.89, 'wordy word']

1.23 type: <class 'float'>
4.56 type: <class 'float'>
7.89 type: <class 'float'>
wordy word type: <class 'str'>
 
1.23 type: <class 'numpy.str_'>
4.56 type: <class 'numpy.str_'>
7.89 type: <class 'numpy.str_'>
wordy word type: <class 'numpy.str_'>
 


# N-dimensional index slicing:  

Python lists are inherently one-dimensional, but you can create lists of lists (i.e., nested lists) to simulate multi-dimensional arrays.

In [11]:
# Creating a 2D array (array of list of lists)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] 
])



print('3x3 matrix:')
print(matrix)
print(' ')

print('1st matrix row:')
print(matrix[0])
print('1st matrix column:')
print(matrix[0:3,0])
print(' ')
print(' ')

print('2nd matrix row:')
print(matrix[1])
print('2nd matrix column:')
print(matrix[0:3,1])
print(' ')
print(' ')

print('3rd matrix row:')
print(matrix[2])
print('3rd matrix column:')
print(matrix[0:3,2])
print(' ')
print(' ')


print('row 2, column 3 value:')
print(matrix[1,2]) 
print(' ')
print(' ')

print('Slicing multiple rows and columns: 2nd & 3rd to 1st & 2nd row column')
submatrix = matrix[1:3, 0:2] 
print(submatrix)
print(' ')
print(' ')



print('Using advanced indexing for 1st and 3rd rows: ')
print(matrix[ [0,2] ])
print('Using advanced indexing:  1st row, 2nd column value & 3rd row, 3rd column value: ')
advanced_index = matrix[[0, 2], [1, 2]]  # Accessing elements at (0,1) and (2,2)
print(advanced_index)

3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
1st matrix row:
[1 2 3]
1st matrix column:
[1 4 7]
 
 
2nd matrix row:
[4 5 6]
2nd matrix column:
[2 5 8]
 
 
3rd matrix row:
[7 8 9]
3rd matrix column:
[3 6 9]
 
 
row 2, column 3 value:
6
 
 
Slicing multiple rows and columns: 2nd & 3rd to 1st & 2nd row column
[[4 5]
 [7 8]]
 
 
Using advanced indexing for 1st and 3rd rows: 
[[1 2 3]
 [7 8 9]]
Using advanced indexing:  1st row, 2nd column value & 3rd row, 3rd column value: 
[2 9]


# Loops and List Comprehension

Like most languages, we can write loops in Python. One of the most standard loops is a for loop, so we'll focus on that one. Below is a 'standard' way of writing a 'for' loop. We'll do something simple, where all we want is to get the square of each number in the array.

## First Let's discuss for-loop basics

In [12]:
# First, let's use "for" and "in"


x = np.linspace(0,20,5)

for ii in x:
    print('ii:' , ii)
    print(' ')


ii: 0.0
 
ii: 5.0
 
ii: 10.0
 
ii: 15.0
 
ii: 20.0
 


In [13]:
# next, let's practice using the "range" function
 
for ii in range( len(x)  ) : 
    print('ii:' , ii)
    print('x[ii]:' , x[ii])
    print(' ')

ii: 0
x[ii]: 0.0
 
ii: 1
x[ii]: 5.0
 
ii: 2
x[ii]: 10.0
 
ii: 3
x[ii]: 15.0
 
ii: 4
x[ii]: 20.0
 


In [14]:
# next, let's practice using "enumerate":

for ii,nn in enumerate(x):
    print('ii:',ii)
    print('nn:',nn)
    print(' ')

ii: 0
nn: 0.0
 
ii: 1
nn: 5.0
 
ii: 2
nn: 10.0
 
ii: 3
nn: 15.0
 
ii: 4
nn: 20.0
 


# Depending on your preference, there's more than one way to do a for-loop!

# what about for-loops in for-loops?

## Sometimes, you may have to iterate over numerous arrays to perform tasks. Give an example... :

In [15]:
y = np.logspace(1, 3, 3)

for ii in range(len(x)):
    
    for jj in range(len(y)):
        
        print('ii & jj:' , ii, ',', jj)
        
        print('x[ii] &  y[jj]:', x[ii], ',', y[jj])
        
        print(' ')

ii & jj: 0 , 0
x[ii] &  y[jj]: 0.0 , 10.0
 
ii & jj: 0 , 1
x[ii] &  y[jj]: 0.0 , 100.0
 
ii & jj: 0 , 2
x[ii] &  y[jj]: 0.0 , 1000.0
 
ii & jj: 1 , 0
x[ii] &  y[jj]: 5.0 , 10.0
 
ii & jj: 1 , 1
x[ii] &  y[jj]: 5.0 , 100.0
 
ii & jj: 1 , 2
x[ii] &  y[jj]: 5.0 , 1000.0
 
ii & jj: 2 , 0
x[ii] &  y[jj]: 10.0 , 10.0
 
ii & jj: 2 , 1
x[ii] &  y[jj]: 10.0 , 100.0
 
ii & jj: 2 , 2
x[ii] &  y[jj]: 10.0 , 1000.0
 
ii & jj: 3 , 0
x[ii] &  y[jj]: 15.0 , 10.0
 
ii & jj: 3 , 1
x[ii] &  y[jj]: 15.0 , 100.0
 
ii & jj: 3 , 2
x[ii] &  y[jj]: 15.0 , 1000.0
 
ii & jj: 4 , 0
x[ii] &  y[jj]: 20.0 , 10.0
 
ii & jj: 4 , 1
x[ii] &  y[jj]: 20.0 , 100.0
 
ii & jj: 4 , 2
x[ii] &  y[jj]: 20.0 , 1000.0
 


# what if we did this in the opposite order? y first then x?

In [16]:
y = np.logspace(1, 3, 3)


    
for jj in range(len(y)):
    for ii in range(len(x)):    
        
        print('ii & jj:' , ii, ',', jj)
        
        print('x[ii] &  y[jj]:', x[ii], ',', y[jj])
        
        print(' ')

ii & jj: 0 , 0
x[ii] &  y[jj]: 0.0 , 10.0
 
ii & jj: 1 , 0
x[ii] &  y[jj]: 5.0 , 10.0
 
ii & jj: 2 , 0
x[ii] &  y[jj]: 10.0 , 10.0
 
ii & jj: 3 , 0
x[ii] &  y[jj]: 15.0 , 10.0
 
ii & jj: 4 , 0
x[ii] &  y[jj]: 20.0 , 10.0
 
ii & jj: 0 , 1
x[ii] &  y[jj]: 0.0 , 100.0
 
ii & jj: 1 , 1
x[ii] &  y[jj]: 5.0 , 100.0
 
ii & jj: 2 , 1
x[ii] &  y[jj]: 10.0 , 100.0
 
ii & jj: 3 , 1
x[ii] &  y[jj]: 15.0 , 100.0
 
ii & jj: 4 , 1
x[ii] &  y[jj]: 20.0 , 100.0
 
ii & jj: 0 , 2
x[ii] &  y[jj]: 0.0 , 1000.0
 
ii & jj: 1 , 2
x[ii] &  y[jj]: 5.0 , 1000.0
 
ii & jj: 2 , 2
x[ii] &  y[jj]: 10.0 , 1000.0
 
ii & jj: 3 , 2
x[ii] &  y[jj]: 15.0 , 1000.0
 
ii & jj: 4 , 2
x[ii] &  y[jj]: 20.0 , 1000.0
 


# let's use a for loop to iterative perform a task and add values to an empty list:

In [17]:
x=np.linspace(0,10,11)

#let's make a blank list that we'll append to.
x_2=[]
print('x_2 before for loop:',x_2)
print('')
# we can append new numbers to our blank list using a "for loop" which
# will look at every entry in the list independently
for i in x:
    print('i:',i,' ; ', 'i * i:', i*i)
    i_2=i * i
    x_2.append( i_2 )
print('')
print ('x_2 after for loop:',x_2)

x_2 before for loop: []

i: 0.0  ;  i * i: 0.0
i: 1.0  ;  i * i: 1.0
i: 2.0  ;  i * i: 4.0
i: 3.0  ;  i * i: 9.0
i: 4.0  ;  i * i: 16.0
i: 5.0  ;  i * i: 25.0
i: 6.0  ;  i * i: 36.0
i: 7.0  ;  i * i: 49.0
i: 8.0  ;  i * i: 64.0
i: 9.0  ;  i * i: 81.0
i: 10.0  ;  i * i: 100.0

x_2 after for loop: [0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]


# Let's say we only want to perform an operation on the first 5 elements in x, we can run our for loop like so with the "range" command

In [18]:
print('for loop for first 5 elements in list:')
x_2=[]
for i in range(5):
    print('i:',i,' ; ', 'x[i] * i:', x[i]*i)
    x_2.append( x[i] * i )
print(x_2)    
print(' ')
# we can also do this for different ranges

print('for loop for 3rd to 7th elements in list:')
x_2=[]
for i in range(3,7):
    print('i:',i,' ; ', 'x[i] * i:', x[i]*i)
    x_2.append( x[i] * i )
print(x_2)    
print(' ')

for loop for first 5 elements in list:
i: 0  ;  x[i] * i: 0.0
i: 1  ;  x[i] * i: 1.0
i: 2  ;  x[i] * i: 4.0
i: 3  ;  x[i] * i: 9.0
i: 4  ;  x[i] * i: 16.0
[0.0, 1.0, 4.0, 9.0, 16.0]
 
for loop for 3rd to 7th elements in list:
i: 3  ;  x[i] * i: 9.0
i: 4  ;  x[i] * i: 16.0
i: 5  ;  x[i] * i: 25.0
i: 6  ;  x[i] * i: 36.0
[9.0, 16.0, 25.0, 36.0]
 


# List comprehension style of for-looping

While that loop works, even this pretty simple example can be condensed into something a bit shorter. We have to set up a blank list, and then after that, the loop itself was 3 lines, so just getting the squares of all these values took 4 lines. We can do it in one with list comprehension.

This is basically a different way of writing a for loop, and will return a list, so we don't have to set up an empty list for the results.

In [19]:
x=np.linspace(0,10,11)
print ('x:',x)
print(' ')

x_2 = [ i*i for i in x ]
print ('x_2:',x_2)

x: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 
x_2: [0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]


# Dictionaries

Dictionaries are another way of storing a large amount of data in Python, except instead of being referenced by an ordered set of numbers like in a list, they are referenced by either strings/characters or numbers, referred to as keys.

In [20]:
x={}
print('x:',x)
print(' ')

x['answer']=42
print('x:',x)
print(' ')

print (x['answer'])

x: {}
 
x: {'answer': 42}
 
42


These are particularly useful if you'll have a handful of values you'd like to call back to often. For an astronomy example, we can set up a dictionary that contains the absolute magnitude of the Sun in a bunch of bands (from Binney & Merrifield). We can now have a code that easily calls absolute magnitudes whenever needed using that dictionary.

We can also list out the dictionary, if needed, with AbMag.items(). There's some other tools for more advanced tricks with dictionaries, but this covers the basics.

In [21]:
AbMag={'U':5.61, 'B':5.48, 'V':4.83, 'R':4.42, 'I':4.08}
print(AbMag)
print('')

print('printing specific entries by using a specific key:')
print(AbMag['V'])
print('')

print('printing all entries:')
print (AbMag.items()) 
print('')

print('printing all keys')
print (AbMag.keys()) 
print('')

print('printing all values')
print (AbMag.values()) 
print('')



{'U': 5.61, 'B': 5.48, 'V': 4.83, 'R': 4.42, 'I': 4.08}

printing specific entries by using a specific key:
4.83

printing all entries:
dict_items([('U', 5.61), ('B', 5.48), ('V', 4.83), ('R', 4.42), ('I', 4.08)])

printing all keys
dict_keys(['U', 'B', 'V', 'R', 'I'])

printing all values
dict_values([5.61, 5.48, 4.83, 4.42, 4.08])



# Functions:

At a certain point you'll be writing the same bits of code over and over again. That means that if you want to update it, you'll have to update it in every single spot you did the same thing. This is.... less than optimal use of time, and it also means it's really easy to screw up by forgetting to keep one spot the same as the rest.


# Let's go over functions basics

In [22]:
def function_name_A(input_value_1, input_value_2,input_value_3):
    ''' Before functions that you write, you should include "Docstrings" which contain some 
    information about what this function does, what inputs are necessary for it to be used,
    and what outputs should be expected from its usage. 
    
    To begin a docstring, use three sets of quotes ('' or "" both work) and write in the 
    space in between the 3 sets of quotes.
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------
    Inputs:
    In this particular function, we have three input arguments:
        - input_value_1: type, anything you want
        - input_value_2: type, anything you want
        - input_value_3: type, anything you want
        
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------    
    Outputs: 
        print statements only, no output values
    '''
    
    
    # now add some code to do things with the three input values
    print('input_value 1:',input_value_1)
    print('input_value 2:',input_value_2)
    print('input_value 3:',input_value_3)

# How to view docstrings in jupyter notebook (this works with *ANY* function, if that function has docstrings):

## First, type the name of the function you'd like to use, then place your cursor inside the parenthesis and type 'shift + tab'. This should bring up a window like:

<img src="./images/docstring1.png" width="100%">

# Second, if you click the "^" symbol in the small window, it'll open up a larger, scrollable window to read the full docstrings of the desired function:

<img src="./images/docstring2.png" width="100%">

# Let's practice using our custom functions:

In [23]:
# example usage
function_name_A( input_value_1='A', 
                input_value_2=2, 
                input_value_3=True)

input_value 1: A
input_value 2: 2
input_value 3: True


In [24]:
def function_name_B(input_value_1, input_value_2,input_value_3,
                    set_value_1 = 4.56 ):
    ''' 
    In this particular function, we now have our original three 
    input arguments from before (function_name_A):
        - input_value_1: type, anything you want
        - input_value_2: type, anything you want
        - input_value_3: type, anything you want
        
    We also have another input argument called "set_value_1".
    In this particular function, we have set_value_1 = 4.56, 
    meaning that it is "hard-coded" to have that value. 
    Unless we define it as otherwise when using this function, 
    it'll have that value associated with it.
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------
    Inputs:
    In this particular function, we have three input arguments:
        - input_value_1: type, anything you want
        - input_value_2: type, anything you want
        - input_value_3: type, anything you want
        - set_value_1: type, float or anything that you want
        
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------    
    Outputs: 
        print statements only, no output values
    '''    
    
    # now add some code to do things with the three input values
    print('input_value 1:',input_value_1)
    print('input_value 2:',input_value_2)
    print('input_value 3:',input_value_3)
    print('set_value 1:',set_value_1)

In [25]:
# example usage
function_name_B(input_value_1='A', 
                input_value_2=2, 
                input_value_3=True) # note: we're not defining "set_value_1" here

input_value 1: A
input_value 2: 2
input_value 3: True
set_value 1: 4.56


In [26]:
# example usage
function_name_B(input_value_1='A', 
                input_value_2=2, 
                input_value_3=True,
               set_value_1 = 'something else now')

input_value 1: A
input_value 2: 2
input_value 3: True
set_value 1: something else now


In [27]:
def function_name_C(input_value_1, input_value_2,input_value_3,
                    set_value_1=4.56,
                    optional_value=None):
    
    ''' 
    In this particular function, we now have our original four
    input arguments from before (function_name_B):
        - input_value_1: type, anything you want
        - input_value_2: type, anything you want
        - input_value_3: type, anything you want
        - set_value_1: type, float or anything that you want        
        
    We also have another input argument called "optional_value".
    In this particular function, we have optional_value = None, 
    meaning that it is "hard-coded" to have that value. 
    Unless we define it as otherwise when using this function, 
    it'll have that value associated with it.
    
    A NoneType object has a value as the name suggests: None.
    It does nothing and has no value associated with it. 
    We can check the type of this input and do something if 
    it is NoneType or if it is not NoneType:
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------
    Inputs:
        - input_value_1: type, anything you want
        - input_value_2: type, anything you want
        - input_value_3: type, anything you want
        - set_value_1: type, float or anything that you want
        - optional_value: type, NoneType or anything that you want        
        
    
    --------------------------------------------------
    --------------------------------------------------
    --------------------------------------------------    
    Outputs: 
        If optional_value is NoneType: print statements only, no output values
        If optional_value is not NoneType: return other 4 input arguments as an output
    '''        
    
    
    if type(optional_value)==type(None):
        print('input_value 1:',input_value_1)
        print('input_value 2:',input_value_2)
        print('input_value 3:',input_value_3)
        print('set_value 1:',set_value_1) 
    if type(optional_value)!=type(None):        
        return input_value_1 , input_value_2 , input_value_3 , set_value_1
        

In [28]:
# example usage
#note set_value_1 & optional flag is not set
output = function_name_C(input_value_1='A', input_value_2=2,input_value_3=True)

print(' ')
print('if we have optional_flag use its default "None" input value, do we have an output:')
print('output:',output)
print('')

input_value 1: A
input_value 2: 2
input_value 3: True
set_value 1: 4.56
 
if we have optional_flag use its default "None" input value, do we have an output:
output: None



In [29]:
# example usage
#note set_value_1 is not set but optional_value is set to a string
output = function_name_C(input_value_1='A', input_value_2=2,input_value_3=True,
                        optional_value='Not None this time')

print(' ')
print('if we have optional_flag use its default "None" input value, do we have an output:')
print('output:',output)
print('')


# example usage
#note set_value_1 is not set but optional_value is set to a boolean
output = function_name_C(input_value_1='A', input_value_2=2,input_value_3=True,
                        set_value_1 = 16, optional_value=False)

print(' ')
print('if we have optional_flag use its default "None" input value, do we have an output:')
print('output:',output)
print('')


# example usage
#note set_value_1 is not set but optional_value is set to a float
output = function_name_C(input_value_1='B', input_value_2=3,input_value_3=False,
                        optional_value=1.23)

print(' ')
print('if we have optional_flag use its default "None" input value, do we have an output:')
print('output:',output)
print('')


# example usage
#note set_value_1 is not set but optional_value is set to a numpy function
output = function_name_C(input_value_1='B', input_value_2=3,input_value_3=False,
                        optional_value=np.sin)

print(' ')
print('if we have optional_flag use its default "None" input value, do we have an output:')
print('output:',output)
print('')

 
if we have optional_flag use its default "None" input value, do we have an output:
output: ('A', 2, True, 4.56)

 
if we have optional_flag use its default "None" input value, do we have an output:
output: ('A', 2, True, 16)

 
if we have optional_flag use its default "None" input value, do we have an output:
output: ('B', 3, False, 4.56)

 
if we have optional_flag use its default "None" input value, do we have an output:
output: ('B', 3, False, 4.56)



# the way we coded function_name_C, "optional_flag" can be ANYTHING but if it is NoneType, then no output is produced, and only print statements are returned as outputs

# Example Functions:

We can try out a function by writing a crude function for the sum of a geometric series.
$$\frac{1}{r} + \frac{1}{r^2} + \frac{1}{r^3} + \frac{1}{r^4} + \ldots $$

Conveniently, so long as r is larger than 1, there's a known solution to this series. We can use that to see that this function works.
$$ \frac{1}{r-1} $$

This means we can call the function repeatedly and not need to change anything. In this case, you can try using this GeoSum function for several different numbers (remember, r>1), and see how closely this works, by just changing TermValue

In [30]:
def GeoSum(r):
    '''
    This function will approximate the geometric sum of an input value "r".
    
    ==========================
    Inputs:
        - r: type int or float
    Outputs:
        - output: type float
                
    '''
    print('r value:',r)
    powers=range(1,11,1) #set up a list for the exponents 1 to 10
    
    terms=[ (1 / ( r**x ) ) for x in powers] #calculate each term in the series
    # note usage of r**x, in python the exponential operation is "**" (not "^")
    
    
    # OR in simpler for-loop terms (not list-comprehension)
    terms = []
    for x in powers:
        value = 1 / ( r**x )
        terms.append( value )
        
    
    output = sum(terms)
    print('geometric sum:',output)
    print(" ")
    
    return output


TermValue=2

result = GeoSum(TermValue)
print('result:',result)

r value: 2
geometric sum: 0.9990234375
 
result: 0.9990234375


# Classes

To steal a good line for this, ["Classes can be thought of as blueprints for creating objects."](https://jeffknupp.com/blog/2014/06/18/improve-your-python-python-classes-and-object-oriented-programming/)

With a class, we can create an object with a whole set of properties that we can access. This can be very useful when you want to deal with many objects with the same set of parameters, rather than trying to keep track of related variables over multiple lists, or even just having a single object's properties all stored in some hard to manage list or dictionary.

Here we'll just use a class that's set up to do some basic math. Note that the class consists of several smaller functions inside of it. The first function, called __init__, is going to be run as soon as we create an object belonging to this class, and so that'll create two attributes to that object, value and square. The other function, powerraise, only gets called if we call it. Try adding some other subfunctions in there to try this out. They don't need to have anything new passed to them to be run.

In [1]:

class SampleClass:
    '''
    This is now an example of using a class object. Below are some helper functions
    
    '''
    # Initializer / Instance attributes
    def __init__(self, value): #run on initial setup of the class, provide a value
        '''
        This is an initializer function. These are used for any initial set up
        that your Class object may require for functionality. Note that the inputs
        are "self" and "value". "self" is a conventional name for the first parameter of inner functions 
        in a class. With "self", you can access and modify the instance's attributes. Why use "self"?
        It's a convention that makes it clear which methods and attributes belong to the class instance.
        It also maintaints its own state, allowing for "object-oriented" programming principles to
        be applied effectively. While "self" is common convention, the first instance can be called anything
        really. For clarity of your code to others who may read it, I reccomend sticking with "self".
        "Value" is the input value upon calling/using the Class object.
        '''
        self.value = value
        self.square = value**2
     # Instance method
    def powerraise(self, powerval): #only run when we call it, provide powerval
        '''
        This function is used to raise a number to a exoponential power.
        The inputs are "self" (see above for explanation) and "poweralv",
        which is the exponential power value used to raise a number's value to.
        Example: input number value=10 ; powerval=3 ;  raisedpower = 10 ^ 3.
        '''
        self.powerval=powerval
        self.raisedpower=self.value**powerval # In python the exponential operation is "**" (not "^")

        
# Creating an Instance (Object)        
MyNum=SampleClass(3) #initialize the function with a "self" value of 3

# Accessing instance attributes
print('assign its value:')
print (MyNum.value) #
print(' ')

print('assign its squared value')
print (MyNum.square)
print('')

# Calling instance methods
print('assign its power value:')
MyNum.powerraise(4) 
print (MyNum.powerval) 
print(' ')

print('assign its value raised to the 4th power')
print (MyNum.raisedpower) 
print('')

print('Combine class functions for a single "Print Statement":')
print (MyNum.value,'^',MyNum.powerval,'=',MyNum.raisedpower)

assign its value:
3
 
assign its squared value
9

assign its power value:
4
 
assign its value raised to the 4th power
81

Combine class functions for a single "Print Statement":
3 ^ 4 = 81
